# Generated by Django 5.2.12 on 2026-03-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Particulier'), ('professional', 'Professionnel')], db_index=True, default='individual', max_length=20),
        ),
    ]
