# Generated by Django 5.2.12 on 2026-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_type_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='merchant_display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='merchant_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
