# Generated by Django 5.2.12 on 2026-03-20 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_wallet', to='core.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_mobile_money_wallet',
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'phone_number'), name='uniq_mobile_money_wallet_per_user_provider_phone')],
            },
        ),
    ]
