# Generated by Django 5.2.12 on 2026-03-19 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents_as_merchant', to=settings.AUTH_USER_MODEL)),
                ('merchant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents_received', to='core.account')),
            ],
            options={
                'db_table': 'payments_payment_intent',
                'ordering': ['-created_at'],
            },
        ),
    ]
